# Imports

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_classification

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, export_text

from sklearn.metrics import classification_report

Creating a synthetic dataset using the 'make_classification' function from the sklearn library.

In [ ]:
np.random.seed(7)

In [ ]:
features, target= make_classification(n_samples= 1000,
                                      n_features= 5,
                                      n_informative= 2,
                                      n_classes= 2,
                                      random_state= 7,
                                      weights= [0.2, 0.8])

data= pd.DataFrame(features, columns= ['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5'])
target= pd.Series(target, name= 'Label')

# EDA

In [ ]:
data.head(3)

   Feature1  Feature2  Feature3  Feature4  Feature5
0 -0.054960 -1.301560 -0.224268  0.352647  0.034843
1 -0.134688 -2.014310 -1.545599  1.282619  0.451417
2 -0.343258 -1.300125  0.064450  1.587025 -0.320819

In [ ]:
target.head(3)

0    1
1    1
2    1
Name: Label, dtype: int64

In [ ]:
data.describe()

          Feature1     Feature2     Feature3     Feature4     Feature5
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.132572     0.018858     0.028136     0.611570    -0.125097
std       0.236290     1.000339     1.452133     1.184158     0.599625
min      -0.686120    -3.205968    -4.170845    -2.852668    -1.936508
25%      -0.315408    -0.643445    -1.081900    -0.159024    -0.556098
50%      -0.199640     0.054963    -0.047022     0.776715    -0.028477
75%       0.053580     0.701060     1.123918     1.395047     0.316396
max       0.624147     3.415729     4.373494     4.745722     1.474055

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Feature1  1000 non-null   float64
 1   Feature2  1000 non-null   float64
 2   Feature3  1000 non-null   float64
 3   Feature4  1000 non-null   float64
 4   Feature5  1000 non-null   float64
dtypes: float64(5)
memory usage: 39.2 KB

In [ ]:
target.value_counts()

Label
1    801
0    199
Name: count, dtype: int64

Use StandardScaler for scaling features to similar range.

In [ ]:
scaler= StandardScaler()
scaled_data= scaler.fit_transform(data)
scaled_data= pd.DataFrame(scaled_data, columns= data.columns)

In [ ]:
scaled_data.head(3)

   Feature1  Feature2  Feature3  Feature4  Feature5
0  0.328624 -1.320630 -0.173903 -0.218765  0.266869
1 -0.008962 -2.033495 -1.084283  0.566972  0.961939
2 -0.892091 -1.319195  0.025020  0.824166 -0.326570

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(scaled_data, target, test_size= 0.2, stratify= target, random_state= 7)

In [ ]:
models= {
    "LR": LogisticRegression(class_weight= 'balanced', random_state= 7),
    "DT": DecisionTreeClassifier(max_depth=3, class_weight= 'balanced',random_state= 7)
}

In [ ]:
for name,model in models.items():
  print(name)

  model.fit(X_train, y_train)
  preds= model.predict(X_test)

  print(classification_report(y_test, preds))

LR
              precision    recall  f1-score   support

           0       0.74      0.93      0.82        40
           1       0.98      0.92      0.95       160

    accuracy                           0.92       200
   macro avg       0.86      0.92      0.89       200
weighted avg       0.93      0.92      0.92       200

DT
              precision    recall  f1-score   support

           0       0.75      0.97      0.85        40
           1       0.99      0.92      0.95       160

    accuracy                           0.93       200
   macro avg       0.87      0.95      0.90       200
weighted avg       0.94      0.93      0.93       200

In [ ]:
print(f"Mean:{scaler.mean_}\nScale:{scaler.scale_}")

Mean:[-0.13257159  0.0188575   0.02813569  0.61157012 -0.12509749]
Scale:[0.23617186 0.99983899 1.45140636 1.18356577 0.59932498]

In [ ]:
print(f"Coefficients:{models["LR"].coef_}\nIntercept:{models["LR"].intercept_}")

Coefficients:[[-2.36071363  0.21969367 -0.28733219  2.36309054 -0.54954606]]
Intercept:[3.523421]

In [ ]:
print(f"{export_text(models["DT"])}")

|--- feature_0 <= 0.73
|   |--- feature_3 <= -1.04
|   |   |--- class: 0
|   |--- feature_3 >  -1.04
|   |   |--- feature_3 <= -1.01
|   |   |   |--- class: 1
|   |   |--- feature_3 >  -1.01
|   |   |   |--- class: 1
|--- feature_0 >  0.73
|   |--- feature_0 <= 0.90
|   |   |--- feature_2 <= 0.02
|   |   |   |--- class: 1
|   |   |--- feature_2 >  0.02
|   |   |   |--- class: 0
|   |--- feature_0 >  0.90
|   |   |--- feature_3 <= -1.18
|   |   |   |--- class: 0
|   |   |--- feature_3 >  -1.18
|   |   |   |--- class: 0